import mongoose from "mongoose";
const Stud = new mongoose.Schema({
    adm:{
        type:Number,
        required:true
    },
    dte:{
        type:String,
        required:true
    },
    fname:{
        type:String,
        required:true
    },
    lname:{
        type:String,
        required:true
    },
    mble:{
        type:Number,
        required:true
    },
    dob:{
        type:String,
        required:true
    },
    dad:{
        type:String,
        required:true
    },
    mom:{
        type:String,
        required:true
    },
    mail:{
        type:String,
        required:true
    },
    branch:{
        type:String,
        required:true
    },
    roll:{
        type:String,
        required:true
    },
    passwd:{
        type:String,
        required:true
    },
    text:{
        type:String,
        required:true
    }
})

export default mongoose.model('student',Stud);